/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.tkms.aist.videorank;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
